# Ensure static assets like images are served correctly
[[redirects]]
  from = "/portfolio/images/*"
  to = "/portfolio/images/:splat"
  status = 200

# Redirect all other paths to the portfolio index
[[redirects]]
  from = "/*"
  to = "/portfolio/index.html"
  status = 200
  force = false
